# Exported from Render on 2024-07-15T14:48:54Z
services:
- type: web
  name: Anomus backend
  runtime: node
  repo: https://github.com/leo-v16/Anomus
  plan: free
  envVars:
  - key: JWT_RESET_TOKEN
    sync: false
  - key: JWT_MAIN_TOKEN
    sync: false
  - key: PORT
    sync: false
  - key: BASE_URL
    sync: false
  - key: MONGODB_URL
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node index.js
version: "1"
